import type { Metadata } from "next";
import ToolShell from "@/components/tools/ToolShell";
import AdsAudit from "@/components/tools/AdsAudit";

export const metadata: Metadata = {
  title: "AI Ads Audit (Free) — Google + Meta | With Hammad",
  description:
    "Paste your Google Ads or Meta Ads account data and get a 0-100 Ads Health Score, prioritized critical/high issues, and a quick-win action plan — generated by AI in under 60 seconds.",
  alternates: { canonical: "/tools/ai-ads-audit" },
};

export default function Page() {
  return (
    <ToolShell
      badge="Free · AI"
      title="AI Ads Audit — Google + Meta"
      subtitle="Paste a snapshot of your ad account — campaign names, top search terms, key metrics — and get a 0-100 Health Score, prioritized issues, and a quick-win action plan. Powered by the same audit framework I run on $999/mo client accounts."
    >
      <AdsAudit />
    </ToolShell>
  );
}
