import type { CaseStudyDetail } from "@/lib/wp-queries";

// ---------------------------------------------------------------------------
// Local, self-contained case-study content (no headless CMS dependency).
// Source of truth: case-studies-content.md. Edit here to update the site.
// Testimonials are intentionally null — the drafted quotes must NOT ship as
// real client words; add them here only once approved.
// ---------------------------------------------------------------------------

const st = (name: string, slug: string) => ({ name, slug });

export const LOCAL_CASE_STUDIES: CaseStudyDetail[] = [
  {
    id: "cs-printo",
    title: "Printo — 3,750 conversions on a single Google Ads rebuild",
    slug: "printo",
    serviceTypes: { nodes: [st("PPC", "ppc"), st("CRO", "cro")] },
    caseStudyFields: {
      clientName: "Printo",
      industry: "Printing / E-commerce",
      servicesUsed: "Google Ads, Performance Max, CRO",
      isHero: true,
      isSample: false,
      showLogo: true,
      clientLogo: null,
      heroMetric: "3,750",
      heroMetricLabel: "Conversions tracked",
      theChallenge:
        "Printo was running one catch-all Google Ads campaign across every product line — box printing, business cards, paper bags, stickers, book printing. Budget was spread thin, impression share was critically low on the highest-intent terms, broad match was draining spend on irrelevant searches, and conversion tracking blurred WhatsApp taps with actual purchases. The result: spend without a clear line to revenue.",
      theStrategy:
        "Restructure for intent and clarity. Split the single campaign into product-specific Search campaigns so budget and messaging matched each buyer's intent. Establish clean conversion tracking that separated genuine purchase/lead actions from low-value taps. Set a defensible Target CPA and let the data — not guesswork — drive bids. Cut waste aggressively with negatives and match-type discipline.",
      theExecution:
        "Broke the catch-all account into tightly themed campaigns and ad groups per product.\nRebuilt responsive search ads with distinct, un-over-pinned headlines per product line.\nLayered in a negative-keyword framework to stop broad-match waste.\nFixed sitelink and tracking issues and set a Target CPA aligned to unit economics.\nIdentified that Arabic search terms converted at a dramatically lower CPA than English — and shifted weight accordingly.",
      metric1: "24,600",
      label1: "Clicks driven",
      metric2: "3,750",
      label2: "Conversions tracked",
      metric3: "AED 42,100",
      label3: "Managed spend",
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  {
    id: "cs-deewan",
    title: "Deewan — +30% leads, −28% CPA across 4 GCC markets",
    slug: "deewan-equipment-trading",
    serviceTypes: {
      nodes: [st("PPC", "ppc"), st("Multi-Market", "multi-market")],
    },
    caseStudyFields: {
      clientName: "Deewan Equipment Trading",
      industry: "B2B / Equipment Trading",
      servicesUsed: "Google Ads, Paid Social, Multi-Market Strategy",
      isHero: false,
      isSample: false,
      showLogo: true,
      clientLogo: null,
      heroMetric: "−28%",
      heroMetricLabel: "Lower cost per acquisition",
      theChallenge:
        "Deewan needed qualified B2B leads across four GCC markets — UAE, Saudi Arabia, Qatar and Bahrain — each with different buyer behavior, language mix, and competition. A single blanket approach was producing inconsistent lead quality and rising costs as spend scaled.",
      theStrategy:
        "Treat each market as its own campaign with localized intent, then concentrate budget where cost-per-lead was lowest and quality highest. Tighten targeting around genuine commercial-intent searches and reduce spend on tyre-kicker traffic.",
      theExecution:
        "Built market-specific campaigns with localized keywords and ad copy across the four countries.\nImplemented conversion tracking to compare lead quality and CPA by market.\nReallocated budget continuously toward the best-performing geos and search themes.\nPruned low-intent terms and refined audience signals to lift lead quality.",
      metric1: "+30%",
      label1: "Increase in leads",
      metric2: "−28%",
      label2: "Lower CPA",
      metric3: "4",
      label3: "GCC markets",
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  {
    id: "cs-good-morning-property",
    title: "Good Morning Property — 80 leads at AED 76 CPL",
    slug: "good-morning-property",
    serviceTypes: {
      nodes: [st("Paid Social", "paid-social"), st("CRO", "cro")],
    },
    caseStudyFields: {
      clientName: "Good Morning Property",
      industry: "Real Estate",
      servicesUsed: "Meta Ads, Lead Generation, Landing Page CRO",
      isHero: false,
      isSample: false,
      showLogo: true,
      clientLogo: null,
      heroMetric: "AED 76.38",
      heroMetricLabel: "Cost per lead",
      theChallenge:
        "In Dubai's crowded, high-cost real-estate market, generating qualified buyer/seller leads without overpaying is hard. The brief: a steady flow of genuine enquiries at a controlled cost per lead.",
      theStrategy:
        "Pair sharp audience targeting with a high-converting lead flow — strong hook, clear offer, fast-loading form — so every dirham of ad spend translated into a real enquiry rather than a wasted click.",
      theExecution:
        "Built audience sets around genuine property-intent signals.\nWrote scroll-stopping ad creative tailored to the offer and locality.\nOptimized the landing page and lead form to cut friction and lift completion rate.\nMonitored lead quality and iterated creative to keep CPL efficient.",
      metric1: "80",
      label1: "Qualified leads",
      metric2: "AED 76.38",
      label2: "Cost per lead",
      metric3: null,
      label3: null,
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  {
    id: "cs-rainbow-printing",
    title: "Rainbow Printing — +50% organic traffic, +27% CVR",
    slug: "rainbow-printing",
    serviceTypes: { nodes: [st("SEO", "seo"), st("CRO", "cro")] },
    caseStudyFields: {
      clientName: "Rainbow Printing Industries",
      industry: "Printing / Manufacturing",
      servicesUsed: "SEO, Content, CRO",
      isHero: false,
      isSample: false,
      showLogo: true,
      clientLogo: null,
      heroMetric: "+50%",
      heroMetricLabel: "Organic traffic growth",
      theChallenge:
        "Strong manufacturing capability, weak organic presence. The site wasn't ranking for the commercial terms buyers actually searched, and the traffic it did get wasn't converting into enquiries at a healthy rate.",
      theStrategy:
        "Win organic visibility on high-intent commercial keywords, then make sure that hard-won traffic converted — pairing SEO with conversion-rate optimization so growth compounded instead of leaking.",
      theExecution:
        "Researched and targeted the commercial keywords with real buyer intent.\nStrengthened on-page SEO, content structure, and technical fundamentals.\nRan CRO improvements on key pages to lift enquiry/conversion rate.\nTracked rankings → traffic → conversions as one connected funnel.",
      metric1: "+50%",
      label1: "Organic traffic growth",
      metric2: "+27%",
      label2: "Lift in conversion rate",
      metric3: null,
      label3: null,
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  // --- Illustrative sample projects (isSample: true) ---------------------
  // Demonstrate methodology only. Generic clients, representative metrics.
  {
    id: "cs-sample-saas-de",
    title: "B2B SaaS (Germany) — −34% cost per qualified demo",
    slug: "sample-b2b-saas-germany-google-ads",
    serviceTypes: { nodes: [st("PPC", "ppc"), st("CRO", "cro")] },
    caseStudyFields: {
      clientName: "B2B SaaS scale-up",
      industry: "B2B SaaS · Germany",
      servicesUsed: "Google Ads, Search, Landing-page CRO",
      isHero: false,
      isSample: true,
      showLogo: false,
      clientLogo: null,
      heroMetric: "−34%",
      heroMetricLabel: "Lower cost per qualified demo",
      theChallenge:
        "A Series-A SaaS company was spending heavily on Google Ads but booking few qualified demos. Broad keywords pulled in free-tier hunters and students, the German ad copy was a literal translation that ignored local buying language, and 'demo request' and 'newsletter signup' were counted as the same conversion — so Smart Bidding optimized toward the cheap, low-value action.",
      theStrategy:
        "Re-anchor the account on commercial-intent German keywords, separate a true 'qualified demo' conversion from soft signups so bidding chases revenue, and tighten the funnel from click to booked demo with a dedicated landing page.",
      theExecution:
        "Rebuilt the keyword set around high-intent German commercial terms and added an aggressive negative list (free, kostenlos, jobs, tutorial).\nSplit conversions into primary (qualified demo booked) and secondary (signup) so Smart Bidding chased real pipeline.\nRewrote ad copy in native German buying language, not translation.\nShipped a focused demo landing page and ran CRO on the form to cut friction.",
      metric1: "−34%",
      label1: "Cost per qualified demo",
      metric2: "+58%",
      label2: "Qualified demos booked",
      metric3: "2.1×",
      label3: "Pipeline from paid search",
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  {
    id: "cs-sample-d2c-fr",
    title: "D2C brand (France) — 3.1× ROAS on Meta Advantage+",
    slug: "sample-d2c-france-meta",
    serviceTypes: {
      nodes: [st("Paid Social", "paid-social"), st("CRO", "cro")],
    },
    caseStudyFields: {
      clientName: "D2C lifestyle brand",
      industry: "D2C E-commerce · France",
      servicesUsed: "Meta Ads, Advantage+, Creative testing",
      isHero: false,
      isSample: true,
      showLogo: false,
      clientLogo: null,
      heroMetric: "3.1×",
      heroMetricLabel: "Return on ad spend",
      theChallenge:
        "A French D2C brand had a fragmented Meta account — dozens of overlapping ad sets competing against each other, a single hero creative fatiguing fast, and prospecting blended with retargeting so true new-customer cost was invisible. ROAS was sliding as spend scaled.",
      theStrategy:
        "Consolidate into Advantage+ to let Meta's AI find buyers, separate prospecting from retargeting so the funnel is measurable, and feed the system a steady pipeline of fresh creative since AI-led delivery fatigues creative faster.",
      theExecution:
        "Collapsed overlapping ad sets into a consolidated Advantage+ structure.\nSplit prospecting (Advantage+) from a dedicated retargeting campaign to see true new-customer CAC.\nBuilt a rolling creative pipeline (UGC + static + video hooks) and retired ads on a frequency/CTR threshold.\nTightened the product-page and checkout experience to lift conversion on the traffic Meta sent.",
      metric1: "3.1×",
      label1: "Blended ROAS",
      metric2: "−25%",
      label2: "Cost per acquisition",
      metric3: "+42%",
      label3: "New-customer revenue",
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
  {
    id: "cs-sample-proserv-nl",
    title: "Professional services (Netherlands) — 2.4× qualified leads",
    slug: "sample-proservices-netherlands-leadgen",
    serviceTypes: { nodes: [st("PPC", "ppc"), st("SEO", "seo")] },
    caseStudyFields: {
      clientName: "Professional services firm",
      industry: "Professional Services · Netherlands",
      servicesUsed: "Google Ads, SEO, Landing-page CRO",
      isHero: false,
      isSample: true,
      showLogo: false,
      clientLogo: null,
      heroMetric: "2.4×",
      heroMetricLabel: "More qualified leads",
      theChallenge:
        "A Dutch professional-services firm relied on referrals and had no predictable inbound. Paid search sent traffic to the homepage, organic visibility was thin on the services that actually paid, and there was no way to tell which enquiries were qualified.",
      theStrategy:
        "Build one integrated lead engine: paid search to capture in-market demand now, SEO to compound free demand over time, and service-specific landing pages with proper lead tracking so quality — not just volume — is visible.",
      theExecution:
        "Launched tightly-themed Search campaigns per service line pointing at intent-matched landing pages instead of the homepage.\nBuilt SEO content around the high-value commercial queries and fixed technical/on-page gaps.\nAdded lead-quality tracking (qualified vs. unqualified) so spend shifted to what booked real work.\nRan CRO on the enquiry forms to lift completion rate.",
      metric1: "2.4×",
      label1: "Qualified leads per month",
      metric2: "−31%",
      label2: "Cost per qualified lead",
      metric3: "+46%",
      label3: "Organic enquiry traffic",
      metric4: null,
      label4: null,
      metric5: null,
      label5: null,
      testimonialQuote: null,
      testimonialName: null,
      testimonialTitle: null,
      testimonialLinkedin: null,
      galleryNote: null,
    },
  },
];
